### ISSUE TITLE
Forkした人がカスタマイズしやすいような説明文があるとよい

### ISSUE THREAD

**Issue by irasally** [codeforsapporo/papamama#28]
他の地域でpapamamaをカスタマイズする場合に、どこを変えればよいのかがわかると利用しやすいのではないかと思います。

5374では
https://github.com/codeforkanazawa-org/5374/blob/master/LOCALIZE.md

このようなファイルが準備されていました。

ここまでかっちりしていなくても、READMEに記述があるだけでも違うかな？と思いました。

**Comment by irasally** [comment]
* カスタマイズするには ``` data ```フォルダ以下の自分の地域に合わせて作成する
* データの定義については、以下を参照 
https://github.com/codeforsapporo/papamama/blob/master/doc/dataSpecification.xls

で合っていますか？？

あってそうなら上記をREADMEに追加するというのはどうでしょう。

**Comment by irasally** [comment]
もし、READMEに追加するだけでよいのであれば、修正してたたき台のPR出します〜

**Comment by yuskesuzki** [comment]
data の変更以外だと、初期表示位置の設定で index.js の変数 init_center_coords、bing_api_key の変更が必要となります。

**Comment by irasally** [comment]
なるほどです。
ちょっと直してみますね。

**Comment by irasally** [comment]
対応していただき、ありがとうございましたー！
